
<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <?php echo Mage::helper('sagepaymentsce')->__('<strong style="color:#EA7601;">Sage Payment Solutions CE v%s </strong> <br>Need help? Got feedback?  Browse ebizmarts <a href="http://ebizmarts.com/forums/view/3" target="_blank">forums</a>', $this->getVersion())?>
    <img src="http://ebizmarts.com/extension-logo.php?<?php echo $this->getPxParams(); ?>" height="1" width="1" />
    </h4>
</div>
