<ul class="selector_list">
<?php foreach ($this->getItems() as $_item):?>
    <li>
        <?php if ($_item->getIsCurrent()): ?>
			<span class="adj-nav-category-current"><?php echo $_item->getLabel() ?></span>
        <?php  else: ?>
		
			<?php if (Mage::getStoreConfig('design/adjnav/reload_categories')) : ?>
					<a id="cat-<?php echo $_item->getCategoryId()?>" href="?dir=desc&p=clear&cat=<?php echo $_item->getCategoryId()?>" class="adj-nav-pad<?php echo $_item->getLevel()?>"><?php echo $_item->getLabel() ?></a>
			<?php else : ?>
					<a onclick="return false;" id="cat-<?php echo $_item->getCategoryId()?>" href="<?php echo $this->htmlEscape($_item->getUri()) ?>" class="adj-nav-category adj-nav-pad<?php echo $_item->getLevel()?>"><?php echo $_item->getLabel() ?></a>
			<?php endif; ?>			
			
			<?php if($_item->getCount()): ?>  
				(<?php echo $_item->getCount() ?>) 
			<?php endif ?>
		<?php endif ?>
    </li>
<?php endforeach ?>
</ol>