<?php
/**
 * Product:     Layered Navigation Pro - 07/06/12
 * Package:     AdjustWare_Nav_2.4.2_0.1.4_8_300402
 * Purchase ID: QmqwcKnSEMUDkX35fJBKkoOUk2rsivOit75vaVFw7E
 * Generated:   2012-06-12 14:40:26
 * File path:   app/design/frontend/base/default/template/adjnav/layer_pager.phtml
 * Copyright:   (c) 2012 AITOC, Inc.
 */
?>
<?php
/*
 * Adding javascript include
 */
if ('ajax' != Mage::app()->getRequest()->getControllerName())
{
    if(Aitoc_Aitsys_Abstract_Service::get()->isMagentoVersion('>=1.4')):
    else:
    ?>
    <script>adj_nav_toolbar_init()</script>
    <?php if(Mage::helper('adjnav')->isPageAutoload()):?>

    <script type="text/javascript">
        adj_nav_page_autoload_init();
    </script>

    <?php endif; ?>
    <?php
    endif;
}
?>