<?php
/**
 * @see Ebizmarts_SagePaySuite_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="sagepay-payment-notice">
	<img src="http://ebizmarts.com/extension-logo.php?<?php echo $this->getPxParams(); ?>" />
    <h4>
        <?php echo $this->__('<strong style="color:#EA7601;">Sage Pay Suite Community Edition v%s by</strong> <a target="_blank" href="http://ebizmarts.com"><strong>ebizmarts</strong></a>', $this->getSagePaySuiteVersion())?>
    </h4>
    <p>
        <a target="_blank" href="http://ebizmarts.com"><strong>ebizmarts</strong></a>  is a <strong>Sage Pay</strong> Approved Partner <a target="_blank" href="https://support.sagepay.com/apply/default.aspx?partnerID=01bf51f9-0dcd-49dd-a07a-3b1f918c77d7">Get a Sage Pay Account Now!</a>
    </p>
    <p>
        <?php echo $this->__("Need help? Got feedback? Browse ebizmarts' <a target=\"_blank\" href=\"http://ebizmarts.com/forums/view/2\">support forums</a>."); ?>
    </p>
</div>

<?php
	$notloaded = null;
	foreach($this->getCheckExtensions() as $_ext):
?>
<?php if(!extension_loaded($_ext)): ?>
		<?php $notloaded .= '<li class="error-msg">PHP extension <strong>'.$_ext.'</strong> is missing on your server.</li>'; ?>
<?php endif; ?>
<?php endforeach; ?>

<?php if(!is_null($notloaded)): ?>
	<ul id="not-loaded-exts" class="messages"><?php echo $notloaded; ?></ul>
<?php endif; ?>