<?php
/**
 * Product:     Layered Navigation Pro - 16/08/12
 * Package:     AdjustWare_Nav_2.4.7_0.1.4_8_357526
 * Purchase ID: RtE0qeQE7RRjsdRvhv07l9cGxzFoZAJ502qOJCvubx
 * Generated:   2012-12-20 08:02:01
 * File path:   app/design/frontend/base/default/template/adjnav/filter_price_slider.phtml
 * Copyright:   (c) 2012 AITOC, Inc.
 */
?>
<?php
    if(Aitoc_Aitsys_Abstract_Service::get()->isMagentoVersion('>=1.4')):
?>


<?php
//todo: move logic to the block
    list($min,$max) = $this->_filter->getMinMaxPriceInt();

    list($from,$to) = explode($this->getDelimeter(), $this->_filter->getActiveState());

    $from = floor(max($from, $min));

    if ($to)
    {
        $to   = ceil(min($to, $max));
    }
    else
    {
        $to = $max;
    }

    if ($to<1 && $from<1)
    {
        $to = $max;
    }

    $width = 170;

    if ($max)
    {
        if ($max == $min)
        {
            $firstOffset = 0;
            $secondOffset = $width;
        }
        else
        {
        $firstOffset  = ($from-$min)*$width/($max-$min);
        $secondOffset = ($to-$min)*$width/($max-$min);

        }
    }
    else
    {
        $firstOffset  = 0;
        $secondOffset = 0;
    }

    // due to rounding values might change
    //$from = $firstOffset*$max/$width;
    // $to   = $secondOffset*$max/$width;
?>
<ol>
    <li>
<?php if ($to != $from) :?>
<div id="adj-nav-price-slider<?php echo $this->_filter->getRequestVar()?>" class="adj-nav-slider">
    <div class="handle selected" style="left:<?php echo $firstOffset?>px"></div>
    <div class="handle" style="left:<?php echo $secondOffset?>px"></div>
  </div>
<?php endif;?>

<?php if ($to != $from) :?>
<?php echo $this->__('Range:')?>
<?php echo $this->getSymbol()?><span id="adj-nav-range-from<?php echo $this->_filter->getRequestVar()?>"><?php echo $from?></span>-<?php echo $this->getSymbol()?><span id="adj-nav-range-to<?php echo $this->_filter->getRequestVar()?>"><?php echo $to?></span>
<script type="text/javascript">
    var adj_slider = adj_nav_create_slider(<?php echo $width.', '.$firstOffset.', '.$secondOffset.', '.$min.', '.$max.',"'.$this->_filter->getRequestVar()?>");
</script>

<?php else:?>

<?php echo $this->__('Value:')?>
<?php echo $this->getSymbol()?><span id="adj-nav-range-from<?php echo $this->_filter->getRequestVar()?>"><?php echo $from?></span>

<?php endif;?>
    </li>
</ol>


















<?php
    else:
?>







<?php
//todo: move logic to the block
    $max = $this->_filter->getMaxPriceInt();
    list($from,$to) = explode(',', $this->_filter->getActiveState());
    $from = floor(min($from, $max));
    $to   = ceil(min($to, $max));

    if ($to<1 && $from<1){
        $to = $max;
    }


    $width = 170;

    $firstOffset  = $from*$width/$max;
    $secondOffset = $to*$width/$max;

    // due to rounding values might change
    //$from = $firstOffset*$max/$width;
    // $to   = $secondOffset*$max/$width;
?>
<ol>
    <li>
<div id="adj-nav-price-slider<?php echo $this->_filter->getRequestVar()?>" class="adj-nav-slider">
    <div class="handle selected" style="left:<?php echo $firstOffset?>px"></div>
    <div class="handle" style="left:<?php echo $secondOffset?>px"></div>
  </div>
<?php echo $this->__('Range:')?>
<?php echo $this->getSymbol()?><span id="adj-nav-range-from<?php echo $this->_filter->getRequestVar()?>"><?php echo $from?></span>-<?php echo $this->getSymbol()?><span id="adj-nav-range-to<?php echo $this->_filter->getRequestVar()?>"><?php echo $to?></span>
<script type="text/javascript">
    var adj_slider = adj_nav_create_slider(<?php echo $width.', '.$firstOffset.', '.$secondOffset.', '.$max.',"'.$this->_filter->getRequestVar()?>");
</script>
    </li>
</ol>










<?php
    endif;
?>