<?php
/**
 * Product:     Layered Navigation Pro - 07/06/12
 * Package:     AdjustWare_Nav_2.4.2_0.1.4_8_300402
 * Purchase ID: QmqwcKnSEMUDkX35fJBKkoOUk2rsivOit75vaVFw7E
 * Generated:   2012-06-12 14:40:26
 * File path:   app/design/frontend/base/default/template/adjnav/shopbyjs.phtml
 * Copyright:   (c) 2012 AITOC, Inc.
 */
?>
<?php if(Mage::helper('adjnav')->isModuleEnabled('Aitoc_Aitmanufacturers')):?>
<script type="text/javascript">
var currentShopByAttribute = "<?php echo Mage::registry('shopby_attribute');?>";
var currentShopByAttributeValue = "<?php echo Mage::getSingleton('core/session')->getAitocManufacturersCurrentManufacturerId();?>";
</script>
<?php endif;?>