<?php
/**
 * Product:     Layered Navigation Pro - 16/08/12
 * Package:     AdjustWare_Nav_2.4.7_0.1.4_8_357526
 * Purchase ID: RtE0qeQE7RRjsdRvhv07l9cGxzFoZAJ502qOJCvubx
 * Generated:   2012-12-20 08:02:01
 * File path:   app/design/frontend/base/default/template/adjnav/shopbyjs.phtml
 * Copyright:   (c) 2012 AITOC, Inc.
 */
?>
<?php if(Mage::helper('adjnav')->isModuleEnabled('Aitoc_Aitmanufacturers')):?>
<script type="text/javascript">
var currentShopByAttribute = "<?php echo Mage::registry('shopby_attribute');?>";
var currentShopByAttributeValue = "<?php echo Mage::getSingleton('core/session')->getAitocManufacturersCurrentManufacturerId();?>";
</script>
<?php endif;?>