     <div class="head_result">PERSONAL DETAILS</div>
		<div class="acctn_personal">
		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?> 
		<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate"> 
		<div class="rad_8 btn_block" style="margin:0px;"> 
			<button type="submit" title="<?php echo $this->__('Save Details') ?>" class="button"><span><?php echo $this->__('Save Details') ?></span></button>
		</div>
        <?php echo $this->getBlockHtml('formkey')?>
		  <table width="100%" border="0" cellspacing="0" cellpadding="0">
			
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?> 
			<tr>
				<td>
					<label for="email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
					<input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
				</td>
			</tr>
			<tr>
				<td> 
					<input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label style="display:inline;margin-left:4px;" for="change_password"><?php echo $this->__('Change Password') ?></label>
				</td>
			</tr>
			<tr style="display:none;">
				<td>
				<label for="current_password" class="required"><?php echo $this->__('Current Password') ?><em>*</em></label>
				<input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
          
				</td>
			</tr>
			<tr style="display:none;">
			  <td> 
					<label for="password" class="required"><?php echo $this->__('New Password') ?> <em>*</em> <ins><?php echo $this->__('Password must be at least 6 characters') ?></ins></label>
				  <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
                  </td>
			</tr>
			<tr style="display:none;">
			  <td>
				 <label for="confirmation" class="required"><?php echo $this->__('Confirm Password') ?><em>*</em></label>
				<input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
              </td>
			</tr>
			<tr>
			  <td></td>
			</tr> 
		  </table>
		</form>
		</div>
			
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(1).show();
            $('password').up(1).show();
            $('confirmation').up(1).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(1).hide();
            $('password').up(1).hide();
            $('confirmation').up(1).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>