<div class="head_result">
   <?php echo $this->__('Forgot Your Password?') ?> 
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="acctn_personal">
	<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
		<div class="fieldset"> 
			<p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
			<br/>
			<ul class="form-list">
				<li>
					<label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
					<div class="input-box" style="position:relative;">
						<input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
						<div class="rad_8 btn_block" style="position:absolute;  left: 337px;top: -3px;"> <p class="back-link"><button class="button" type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button></div> 
					</div>
				</li>
				<?php echo $this->getChildHtml('form.additional.info'); ?>
			</ul>
		</div> 		
		
        <div class="buttons-set" style="margin-top:20px;">
			<p class="back-link">
				<a  style="color:#77A33F;" href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a>
			</p>	
		</div> 
</form>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
