 <div class="head_result">
   <?php echo $this->__('Newsletter Subscription') ?> 
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<div class="acctn_personal">
	<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
		<div class="fieldset">
			<?php echo $this->getBlockHtml('formkey')?>
			<ul class="form-list">
				<li class="control">
				<input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
				<label for="subscription" style="display:inline;"><?php echo $this->__('General Subscription') ?></label></li>
				<?php /* Extensions placeholder */ ?>
				<?php echo $this->getChildHtml('customer.form.newsletter.extra')?>
			</ul>
		</div>
		<div class="buttons-set">
		<div class="rad_8 btn_block"> 
			<button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><?php echo $this->__('Save') ?></span></button>
		</div> 
		</div>
	</form>
</div>
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('customer.form.newsletter.extra2')?>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
