<style type="text/css">
div.myaccount-errors *{ color:#77A33F; } 
div.myaccount-errors{ position:relative; color:#77A33F; } 
div.myaccount-errors ul.messages li.error-msg ul{ border:none; #77A33F}  
div.btn_block button{ cursor:pointer;}   
</style>
  <div class="account_content fright">
          <div class="head_result"><?php echo $this->__('CREATE AN ACCOUNT');?></div>
          <div class="create_acctn"> <strong><?php echo $this->__('Benefits of creating an account:');?></strong>
            <ul>
              <li><?php echo $this->__('Proceed through checkout faster') ?></li>
              <li><?php echo $this->__('Track the status of your orders') ?></li>
              <li><?php echo $this->__('Make changes to your account information') ?></li>
              <li><?php echo $this->__('Create and share a wishlist')?></li>
            </ul> 
			<?php echo $this->getChildHtml('form_fields_before')?> 
			<div class="myaccount-errors">
				<?php echo $this->getMessagesBlock()->getGroupedHtml();?>
			</div>
			<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate"> 
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
              <table width="410" border="0" cellspacing="0" cellpadding="0">
			    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
				<tr>
                  <td><label><?php echo $this->__('Email Address*:');?></label>
                      <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
				  </td>
                </tr>
                <tr>
                  <td><label><?php echo $this->__('Confirm Email Address*:');?></label>
                      <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
				  </td>
                </tr>
				
				<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
				<?php if ($_dob->isEnabled()): ?>
					 <?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?> 
				<?php endif ?>
				 <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
				<?php if ($_taxvat->isEnabled()): ?>
					<?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
				<?php endif ?>
				<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
				<?php if ($_gender->isEnabled()): ?>
					<?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?>
				<?php endif ?>
				  <?php if ($this->isNewsletterEnabled()): ?>
                <tr>
                  <td><input id="is_subscribed" value="1"  title="<?php echo $this->__('Sign Up for Newsletter') ?>" name="is_subscribed" type="checkbox" <?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    <div class="ppolicy"><strong><?php echo $this->__('Newsletter signup');?></strong><?php echo $this->__('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris');?> <a href="#"><?php echo $this->__('Privacy Policy');?></a>.</div></td>
                </tr>
				<?php endif;?>
				 <?php if($this->getShowAddressFields()): ?>
				<div class="fieldset">
					<input type="hidden" name="create_address" value="1" />
					<h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
					<ul class="form-list">
						<li class="fields">
							<div class="field">
								<label for="company"><?php echo $this->__('Company') ?></label>
								<div class="input-box">
									<input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
								</div>
							</div>
							<div class="field">
								<label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
								<div class="input-box">
									<input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
								</div>
							</div>
						</li>
					<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
						<li class="wide">
							<label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
							<div class="input-box">
								<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
							</div>
						</li>
					<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
					<?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
						<li class="wide">
							<div class="input-box">
								<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
							</div>
						</li>
					<?php endfor; ?>
						<li class="fields">
							<div class="field">
								<label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
								<div class="input-box">
									<input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
								</div>
							</div>
							<div class="field">
								<label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
								<div class="input-box">
									<select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
										<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
									</select>
									<script type="text/javascript">
									//<![CDATA[
										$('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
									//]]>
									</script>
									<input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
								</div>
							</div>
						</li>
						<li class="fields">
							<div class="field">
								<label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
								<div class="input-box">
									<input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
								</div>
							</div>
							<div class="field">
								<label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
								<div class="input-box">
									<?php echo $this->getCountryHtmlSelect() ?>
								</div>
							</div>
						</li>
					</ul>
					<input type="hidden" name="default_billing" value="1" />
					<input type="hidden" name="default_shipping" value="1" />
				</div>
			<?php endif; ?>
                <tr>
                  <td><label><?php echo $this->__('Password*:')?><ins><?php echo __('Password must be at least 6 characters');?></ins></label>
                   <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" /></td>
                </tr>
                <tr>
                  <td><label>Confirm Password*:</label>
                    <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" /></td>
                </tr>
                <tr>
                  <td></td>
                </tr>
                <tr>
                  <td><div class="rad_8 btn_block">
                      <button type="submit"><span><?php echo $this->__('Create Account');?></span></button>
                    </div></td>
                </tr>
              </table> 
                <?php //echo $this->getChildHtml('form.additional.info'); ?>
                <?php //echo $this->getChildHtml('persistent.remember.me'); ?>
				<?php //echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
            </form>
          </div>
        </div>
        <div class="clear"></div>
	<script type="text/javascript">
		//<![CDATA[
		var dataForm = new VarienForm('form-validate', true);
		<?php if($this->getShowAddressFields()): ?>
		new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
		<?php endif; ?>
		//]]>
	</script>