<div class="head_result">
    <h1><?php echo $this->__('Reset a Password'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<div class="acctn_personal">
	<form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
		<div class="fieldset" style="margin-top: 20px;">
			<ul class="form-list">
				<li class="fields">
					<div class="field">
						<label for="password" class="required" style="padding:2px;"><em>*</em><?php echo $this->__('New Password'); ?></label>
						<div class="input-box">
							<input type="password" class="input-text required-entry validate-password" name="password" id="password" />
						</div>
					</div>
					<div class="field" style="padding-top:10px;">
						<label for="confirmation" class="required" style="padding:2px;"><em>*</em><?php echo $this->__('Confirm New Password'); ?></label>
						<div class="input-box">
							<input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
						</div>
					</div>
				</li>
			</ul>
		</div>
		<div class="buttons-set"> 
			<div class="rad_8 btn_block" style="float:left;margin:12px 0 5px 174px;"> 
				<p class="back-link">
					<button type="submit" class="button" title="<?php echo $this->__('Reset Password'); ?>"><span><span><?php echo $this->__('Reset Password'); ?></span></span></button>
				</p>
			</div>
		</div>
	</form>
</div>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
/*]]>*/
</script>
