<?php $_helper  = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<meta property="og:title" content="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"/>
<meta property="og:type" content="product"/>
<meta property="og:url" content="<?php echo $_product->getProductUrl() ?>"/>
<meta property="og:image" content="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(84,84) ?>"/>
<?php if ($_product->getShortDescription()):?>
<meta property="og:description" content="<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>"/>
<?php endif; ?>
