<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<div class="more-views detail_tn" style="height:458px;">
<?php if (count($this->getGalleryImages()) > 0): ?>
    <div class="btn-prev">
        <a href="javascript:void(0);" class="prev"></a>
    </div>
    <div class="gallery-carousel" style="height:400px;">
        <ul id="thumblist">
        <?php foreach ($this->getGalleryImages() as $_image): ?>
            <li>
                <a rel="{gallery: 'product-gallery', smallimage: '<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(305,456); ?>',largeimage: '<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(510,912); ?>'}" href="javascript:void(0);" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(69,104); ?>" width="69" height="104" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                </a>
            </li>
        <?php endforeach; ?>
        </ul>
        <div class="clear"></div>
    </div>
    <div class="btn-next">
        <a href="javascript:void(0);" class="next"></a>
    </div>
<?php else: ?>
	&nbsp;
<?php endif; ?>
</div>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<div class="product-image product-image-zoom detail_large">
    <a rel='product-gallery' href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(510,912) ?>" class="jqzoom-image">
	<?php
		$_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(305,456).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
		echo $_helper->productAttribute($_product, $_img, 'image');
	?>
    </a>
	<div style="display:none;position:absolute;top:0;left:0;width:inherit;height:inherit;background:#ffffff;opacity:0.6;border-radius:5px;z-index:999;" class="scp-please-wait">
		<img src="<?php echo $this->getSkinUrl('images/preview.gif') ?>" class="v-middle" alt="" style="position:absolute;top:212px;left:141px;"/>
	</div>
</div>
<div class="clear"></div>
<div style="text-align:center; padding:10px 0px 0px 0px;width:307px;float:right;">
    <?php echo $this->__('+ Hover image to zoom') ?>
</div>
<?php else: ?>
<div class="product-image detail_large">
	<?php
		$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(255,456).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
		echo $_helper->productAttribute($_product, $_img, 'image');
	?>
	<div style="display:none;position:absolute;top:0;left:0;width:inherit;height:inherit;background:#ffffff;opacity:0.6;border-radius:5px;" class="scp-please-wait">
		<img src="<?php echo $this->getSkinUrl('images/preview.gif') ?>" class="v-middle" alt="" style="position:absolute;top:212px;left:141px;"/>
	</div>
</div>
<?php endif; ?>
