 <?php if ($this->helper('wishlist')->isAllow()) : ?>
 <div class="head_result"><?php echo __('My Wishlists');?></div>
<div class="acctn_wishlist">
	<?php if ($this->helper('wishlist')->isRssAllow() && $this->hasWishlistItems()): ?>
		<a href="<?php echo $this->helper('wishlist')->getRssUrl($this->getWishlistInstance()->getId()); ?>" class="link-rss"><?php echo $this->__('RSS Feed') ?></a>
	<?php endif; ?>
   <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<form id="wishlist-view-form" action="<?php echo $this->getUrl('*/*/update', array('wishlist_id' => $this->getWishlistInstance()->getId())) ?>" method="post">
 		<?php if ($this->hasWishlistItems()): ?>
				<?php echo $this->getBlockHtml('formkey');?>
				<?php $this->getChild('items')->setItems($this->getWishlistItems()); ?>
				<?php echo $this->getChildHtml('items');?>
				<script type="text/javascript">decorateTable('wishlist-table')</script>
		<?php else: ?>
			 <p class="wishlist-empty"><?php echo $this->__('You have no items in your wishlist.') ?></p> 
		<?php endif ?>
	  <div class="fright">
		<?php echo $this->getChild('control_buttons')->toHtml();?> 
		<div class="clear"></div>
	  </div>
 </form>

  <div class="clear"></div>
</div>
<?php endif ?> 