<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div id="graydirt-container">
	<div id="w960">
		<div id="header_wrapper">
			<?php echo $this->getChildHtml('header') ?>
		</div>
		<div id="main_wrapper">
			<div class="w898">
				<?php echo $this->getChildHtml('global_notices') ?>
				<?php echo $this->getChildHtml('breadcrumbs') ?>
			</div>
			<?php echo $this->getChildHtml('content') ?>
		</div>
		<div id="footer_wrapper">
			<?php echo $this->getChildHtml('footer') ?>
		</div>
		<?php echo $this->getAbsoluteFooter() ?>
	</div>
</div>
<?php echo $this->getChildHtml('before_body_end') ?>
</body>
</html>
