<?php
/**
 * Product:     Layered Navigation Pro - 16/08/12
 * Package:     AdjustWare_Nav_2.4.7_0.1.4_8_357526
 * Purchase ID: RtE0qeQE7RRjsdRvhv07l9cGxzFoZAJ502qOJCvubx
 * Generated:   2012-12-20 08:02:01
 * File path:   app/design/frontend/default/default/template/adjnav/filter_price_default.phtml
 * Copyright:   (c) 2012 AITOC, Inc.
 */
?>
<ol>
<?php foreach ($this->getItems() as $_item): ?>
    <li>
        <a id="<?php echo $_item->getFilter()->getRequestVar() . '-' . $_item->getValueString()?>" onclick="return false;" href="<?php echo $this->getItemUrl($_item); ?>" class="adj-nav-price <?php if ($this->isSelected($_item)) echo 'adj-nav-price-selected';?>" ><?php echo $_item->getLabel() ?></a> (<?php echo ($_item->getCount()>=0?$_item->getCount():$this->getCollectionSize()) ?>)
    </li>
<?php endforeach ?>
</ol>