<?php
/**
 * Product:     Layered Navigation Pro - 16/08/12
 * Package:     AdjustWare_Nav_2.4.7_0.1.4_8_357526
 * Purchase ID: RtE0qeQE7RRjsdRvhv07l9cGxzFoZAJ502qOJCvubx
 * Generated:   2012-12-20 08:02:01
 * File path:   app/design/frontend/default/default/template/adjnav/layer_pager.phtml
 * Copyright:   (c) 2012 AITOC, Inc.
 */
?>
<?php
/*
 * Adding javascript include
 */
if ('ajax' != Mage::app()->getRequest()->getControllerName())
{
    if(Aitoc_Aitsys_Abstract_Service::get()->isMagentoVersion('>=1.4')):
    else:
    ?>
    <script>adj_nav_toolbar_init()</script>
    <?php if(Mage::helper('adjnav')->isPageAutoload()):?>

    <script type="text/javascript">
        adj_nav_page_autoload_init();
    </script>

    <?php endif; ?>
    <?php
    endif;
}
?>