<?php
 
$item = $this->getItem();
$product = $item->getProduct();
?>
<textarea name="description[<?php echo $item->getWishlistItemId() ?>]" rows="3" cols="5" onfocus="focusComment(this)" onblur="focusComment(this)" title="<?php echo $this->__('Comment') ?>"><?php echo ($this->escapeHtml($item->getDescription())) ?></textarea>
<?php if($this->getSortedChildren()): ?>
    <div class="item-manage">
    <?php foreach($this->getSortedChildren() as $childName):?>
        <?php echo $this->getChildHtml($childName, false);?>
    <?php endforeach;?>
    </div>
<?php endif; ?> 