<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<?php if(!$this->isContentMode() && !$this->isMixedMode()) :?>
	<div class="dheader">
		<?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
			<a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
		<?php endif; ?>
		<div class="img_featured">
			<?php if($_imgUrl): ?>
				<img alt="<?php echo $this->htmlEscape($_category->getName()); ?>" src="<?php echo $_imgUrl; ?>">
			<?php endif; ?>
		</div>
		<div class="content_featured">
			<h2><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h2>
			<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
				<p><?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?></p>
			<?php endif; ?>
		</div>
		<div class="clear"></div>
	</div>
<?php endif; ?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
