<div class="logo">
	<?php if ($this->getIsHomePage()):?>
		<h1><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
	<?php else:?>
		<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>">
			<strong><?php //echo $this->getLogoAlt() ?></strong>
			<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
	<?php endif?>
</div>
<div class="top_links">
	<?php echo $this->getChildHtml('topLinks') ?>
	<div id="shop-bag" class="shop_bag">
		<?php echo $this->getChildHtml('cart_sidebar'); ?>
	</div>
</div>
<div class="navigation">
	<ul id="nav">
		<li><a href="#"<?php if ($this->getIsHomePage()):?> class="active"<?php endif; ?>>HOME</a></li>
		<?php echo $this->getChildHtml('topMenu') ?>
	</ul>
	<div class="search">
		<?php echo $this->getChildHtml('topSearch'); ?>
	</div>
</div>
<script type="text/javascript">
	//<![CDATA[
	var bagStatusAnimating = false;
	document.observe("dom:loaded", function(){
		$('shop-bag').observe('click', function(e,el) {
			if (bagStatusAnimating) {
				return false;
			}
			if (el = e.findElement('.status')) {
				if(el.hasClassName('show')){
					Effect.SlideUp('header-bag-items', { duration: 0.5, 
						beforeStart: function(){
							bagStatusAnimating = true;
						},
						afterFinish: function(){
							bagStatusAnimating = false;
						}
					});
				} else {
					Effect.SlideDown('header-bag-items', { duration: 0.5,
						beforeStart: function(){
							bagStatusAnimating = true;
						},
						afterFinish: function(){
							bagStatusAnimating = false;
						}
					});
				}
				el.toggleClassName('show');
				e.stop();
			}
			if (el = e.findElement('.btn-close')) {
				Effect.SlideUp('header-bag-items', { duration: 0.5,
					beforeStart: function(){
						bagStatusAnimating = true;
					},
					afterFinish: function(){
						bagStatusAnimating = false;
					}
				});
				$('header-bag-status').removeClassName('show');
				e.stop();
			}
		});
	});
	//]]>
</script>
<?php if(false): ?>
<div class="header-container">
    <div class="header">
        <?php if ($this->getIsHomePage()):?>
        <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php else:?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>
        <p class="top-promo" title="<?php echo $this->__('Free Shipping on orders over 50$'); ?>"><?php echo $this->__('Free Shipping on orders over 50$'); ?></p>
        <?php echo $this->getChildHtml('topMenu') ?>
    </div>
    <div class="quick-access">
        <?php echo $this->getChildHtml('store_language') ?>
        <p class="welcome-msg"><?php echo $this->getWelcome()?></p>
        <?php echo $this->getChildHtml('topLinks') ?>
    </div>
    <?php echo $this->getChildHtml('topBar') ?>
    <?php echo $this->getChildHtml('topContainer'); ?>
</div>
<?php endif; ?>
