<style type="text/css">
.demo-notice {
    background: none repeat scroll 0 0 #D75F07;
    border: 0 none;
    color: #FFFFFF;
    font-size: 12px;
    line-height: 1.15;
    margin: 0;
    padding: 6px 10px;
    text-align: center;
}
.demo-notice .notice-inner {
    background: none repeat scroll 0 0 transparent;
    padding: 0;
    text-align: center;
    width: auto;
}
.demo-notice .notice-inner p {
    border: 0 none;
    padding: 0;
}
</style>
<?php

/**
 * @var $this Mage_Page_Block_Html_Notices
 */
?>
<?php if ($this->displayNoscriptNotice()): ?>
    <noscript>
        <div class="global-site-notice noscript">
            <div class="notice-inner">
                <p>
                    <strong><?php echo $this->__('JavaScript seems to be disabled in your browser.'); ?></strong><br />
                    <?php echo $this->__('You must have JavaScript enabled in your browser to utilize the functionality of this website.'); ?>
                </p>
            </div>
        </div>
    </noscript>
<?php endif; ?>
<?php if ($this->displayDemoNotice()): ?>
    <div class="global-site-notice demo-notice">
        <div class="notice-inner"><p><?php echo $this->__('This is a demo store. Any orders placed through this store will not be honored or fulfilled.') ?></p></div>
    </div>
<?php endif; ?>
<?php if (Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
    <div class="global-site-notice notice-cookie" id="notice-cookie-block" style="display: none">
        <div class="notice-inner">
            <p><?php echo $this->__('This website requires cookies to provide all of its features. For more information on what data is contained in the cookies, please see our <a href="%s">Privacy Policy page</a>. To accept cookies from this site, please click the Allow button below.', $this->getPrivacyPolicyLink()) ?>
                <button class="button" onclick="allowSaveCookie()"><span><span><?php echo $this->__('Allow');?></span></span></button>
            </p>
        </div>
    </div>
    <script type="text/javascript">
    /* <![CDATA[ */
    function allowSaveCookie() {
        Mage.Cookies.set('<?php echo Mage_Core_Helper_Cookie::IS_USER_ALLOWED_SAVE_COOKIE; ?>', '<?php echo Mage::helper('core/cookie')->getAcceptedSaveCookiesWebsiteIds()?>', new Date(new Date().getTime() + <?php echo Mage::helper('core/cookie')->getCookieRestrictionLifetime() ?> * 1000));
        if (Mage.Cookies.get('<?php echo Mage_Core_Helper_Cookie::IS_USER_ALLOWED_SAVE_COOKIE; ?>')) {
            window.location.reload();
        } else {
            window.location.href = '<?php echo Mage::getUrl('cms/index/noCookies')?>';
        }
    }
    $('notice-cookie-block').show();
    /* ]]> */
    </script>
<?php endif; ?>
