<?php if(true): ?>
<div class="pcontent" style="width:710px;">
	<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
		<span><?php echo $this->__('Sign up for latest news from The Girl in the Green Scarf') ?></span>
		<div class="subscription-email">
			<input type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry-email validate-email" placeholder="<?php echo $this->__('Enter your email address here') ?>" />
		</div>
		<div class="subscription-action">
			<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><?php echo $this->__('Submit') ?></button>
		</div>
		<div class="clear"></div>
	</form>
    <script type="text/javascript">
    //<![CDATA[
		// customized error messages
		Validation.add('required-entry-email', '<?php echo $this->__('Email address is required') ?>', function(v) {
			return !Validation.get('IsEmpty').test(v);
		});
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>
<?php endif; ?>
<?php if(false): ?>
<div class="block block-subscribe">
    <div class="block-title">
        <strong><span><?php echo $this->__('Newsletter') ?></span></strong>
    </div>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="block-content">
            <div class="form-subscribe-header">
                <label for="newsletter"><?php echo $this->__('Sign Up for Our Newsletter:') ?></label>
            </div>
            <div class="input-box">
               <input type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
            </div>
            <div class="actions">
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>
<?php endif; ?>
