<style type="text/css"> 
.buttons{
	float:right;
}
.order-info {
    background: none repeat scroll 0 0 #DEE5E8;
    border: 1px solid #D0CBC1;
    margin: 0 0 8px;
    padding: 4px 8px;
}
.order-info dt, .order-info dd, .order-info ul, .order-info li {
    display: inline;
}
.order-info .current {
    font-weight: bold;
}
.order-info li {
    margin: 0 3px;
}
.order-date {
    margin: 10px 0;
}
.col2-set .col-1 {
    float: left;
    width: 48.5%;
}
.col2-set .col-2 {
    float: right;
    width: 48.5%;
}
.order-info-box h2 {
    font-size: 13px;
    font-weight: bold;
}
address {
    font-style: normal;
    line-height: 1.35;
}
.order-items {
    overflow-x: auto;
    width: 100%;
}
.order-items h2, .order-items h3 {
    clear: none;
    color: #0A263C;
    font-size: 13px;
    font-weight: bold;
    margin: 0 0 5px;
    padding: 0;
}
.data-table {
    border: 1px solid #BEBCB7;
    width: 100%;
}	
.data-table tr.last th, .data-table tr.last td {
    border-bottom: 0 none !important;
}

.data-table thead th {
   /* background: url("<?php echo $this->getSkinUrl();?>images/bkg_th.gif") repeat-x scroll 0 100% #D9E5EE;*/
   background-color:#DFDFE0;
}
.data-table thead th {
    border-right: 1px solid #C2D3E0;
    color: #0A263C;
    font-weight: bold;
    padding: 2px 8px;
    vertical-align: middle;
    white-space: nowrap;
}
.data-table tr.last th, .data-table tr.last td {
    border-bottom: 0 none !important;
}
.data-table tbody th, .data-table tbody td {
    border-bottom: 1px solid #D9DDE3;
    border-right: 1px solid #D9DDE3;
}
.data-table td {
    padding: 3px 8px;
}
caption, th, td {
    font-weight: normal;
    text-align: left;
    vertical-align: top;
}
.nobr {
    white-space: nowrap !important;
}
.order-items .product-name { 
    font-weight: bold !important;
}
.order-items h2, .order-items h3 {
    clear: none;
    color: #0A263C;
    font-size: 13px;
    font-weight: bold;
    margin: 0 0 5px;
    padding: 0;
	font-family:Arial,Helvetica,sans-serif;
}




















	
</style>
<?php $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="head_result"> 
    <div class="buttons"><?php echo $this->getChildHtml('buttons') ?></div>
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<dl class="order-info">
    <dt><?php echo $this->__('About This Order:') ?></dt>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul id="order-info-tabs">
        <?php foreach ($_links as $_link): ?>
            <?php if($_link->getUrl()): ?>
                <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
            <?php else: ?>
                <li class="current"><?php echo $_link->getLabel() ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>
    </dd>
</dl>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<?php if (!$_order->getIsVirtual()): ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping Method') ?></h2>
            </div>
            <div class="box-content">
                <?php if ($_order->getShippingDescription()): ?>
                    <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
                <?php else: ?>
                    <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Billing Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box box-payment">
            <div class="box-title">
                <h2><?php echo $this->__('Payment Method') ?></h2>
            </div>
            <div class="box-content">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
