<?php if ($this->isShowShippingAddress()):?>
<div id="showhide_shipping" style="display:none;">

	<div class="head_area">SHIPPING ADDRESS</div>
	<div class="block_step1">

		<table width="100%" cellspacing="0" cellpadding="0" border="0" id="shipping-new-address-form" <?php if ($this->customerHasAddresses()): ?>style="display:none"<?php endif ?>>
		<tbody>
		<tr valign="top">
			<td>
				<input type="hidden" name="shipping[address_id]" value="<?php echo $this->getShippingAddress()->getId() ?>" id="shipping:address_id" />
			</td>
		</tr>
		<tr valign="top">
			<td>
				<div class="fleft">				
					<label for="shipping:firstname"><?php echo $this->__('First Name') ?>*</label>
					<input type="text" id="shipping:firstname" name="shipping[firstname]" value="<?php echo $this->getShippingAddress()->getShippingFirstname(); ?>" title="<?php echo $this->__('First Name') ?>" class="input-text required-entry" />
				</div>
				<div class="fright">
					<label for="shipping:lastname"><?php echo $this->__('Last Name') ?>*</label>
					<input type="text" id="shipping:lastname" name="shipping[lastname]" value="<?php echo $this->getShippingAddress()->getShippingLastname(); ?>" title="<?php echo $this->__('Last Name') ?>" class="input-text required-entry" />
				</div>
			</td>
		</tr>
		
		<?php if($this->configData['show_company']): ?>
		<tr valign="top">
			<td>
				<div class="fleft">	
					<label for="shipping:company"><?php echo $this->__('Company') ?></label>
					<input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
				</div>
			</td>
		</tr>
		<?php endif; ?>
		
		
		<tr valign="top">
			<td>			
				<label for="shipping:street1"><?php echo $this->__('Address') ?> *</label>				
				<input type="text"  style="margin:0px 0px 8px 0px;" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingStreet(1)) ?>" class="required-entry input-text"/>
				<?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
				<input type="text" title="<?php echo $this->__('Street Address '.$_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingStreet($_i)) ?>" class="input-text" />
				<?php endfor ?>
			</td>
		</tr>
		
		<?php if ($this->configData['show_city']):?>
		<tr valign="top">
			<td>
				<label for="shipping:city"><?php echo $this->__('City') ?> *</label>
				<input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingCity()) ?>" class="required-entry input-text" id="shipping:city" />
			</td>
		</tr>
		<?php endif;?>
		
		<?php if($this->configData['show_fax']): ?>
		<tr valign="top">
			<td>
				<label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
				<input type="text" name="shipping[fax]" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text" id="shipping:fax" />
			</td>
		</tr>
		<?php endif; ?>
		
		<?php if($this->configData['show_telephone']): ?>
		<tr valign="top">
			<td>
				<label for="shipping:telephone"><?php echo $this->__('Telephone') ?> *</label>
				<input type="text" name="shipping[telephone]" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="required-entry input-text" id="shipping:telephone" />
			</td>
		</tr>
		<?php endif; ?>
		
		<tr valign="top">
			<td>
				<div class="fleft">
					<?php if ($this->configData['show_zipcode']):?>
						<label for="shipping:postcode"><?php echo $this->__('Postcode') ?> *</label>
						<input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingZipcode()) ?>" class="validate-zip-international required-entry input-text"/>
					<?php endif; ?>
				</div>
				<div class="fright">
					<label for="shipping:country_id"><?php echo $this->__('Country') ?>*</label>
					<?php echo $this->getCountryHtmlSelect('shipping') ?>
				</div>
			</td>
		</tr>
		
		<?php if ($this->configData['show_region']):?>	
		<tr valign="top">
			<td>			
				<label for="billing:region"><?php echo $this->__('State/Province') ?>*</label>
				<select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;width:275px;" >
					<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
				</select>
				<script type="text/javascript">
						$('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getShippingRegionId() ?>");
				</script>
				<input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none" />
			</td>
		</tr>
		<?php endif?>	
		
		<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
			<tr valign="top">
				<td>
					<input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" <?php if ($this->getShippingAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> /> <label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
				</td>
			</tr>
		<?php else:?>
			<input type="hidden" name="shipping[save_in_address_book]" value="1" />
		<?php endif;?>
		
		</tbody>
		</table>

		<?php /* ?>
		<div id="showhide_shipping" style="display:none;">
			<h3 id="shipping_step_header" class="step_2"><?php echo($this->__("SHIPPING ADDRESS")); ?></h3>
			<?php if ($this->customerHasAddresses()): ?>
			  <p><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></p>
			  <p><?php echo $this->getAddressesHtmlSelect('shipping') ?></p>
			<?php endif ?>
			<fieldset class="group-select" id="shipping-new-address-form" <?php if ($this->customerHasAddresses()): ?>style="display:none"<?php endif ?>>
				<input type="hidden" name="shipping[address_id]" value="<?php echo $this->getShippingAddress()->getId() ?>" id="shipping:address_id" />
				<ul>
					<li>
						<div class="input-box">
							<label for="shipping:firstname"><?php echo $this->__('First Name') ?><span class="required">*</span></label><br/>
							<input type="text" id="shipping:firstname" name="shipping[firstname]" value="<?php echo $this->getShippingAddress()->getShippingFirstname(); ?>" title="<?php echo $this->__('First Name') ?>" class="input-text required-entry" />
						</div>
						<div   class="input-box">
							<label for="shipping:lastname"><?php echo $this->__('Last Name') ?><span class="required">*</span></label><br/>
							<input type="text" id="shipping:lastname" name="shipping[lastname]" value="<?php echo $this->getShippingAddress()->getShippingLastname(); ?>" title="<?php echo $this->__('Last Name') ?>" class="input-text required-entry" />
						</div>
					</li>
					<li class="input-box">			
						<?php if($this->configData['show_company']): ?>
						<div class="input-box">
							<label for="shipping:company"><?php echo $this->__('Company') ?></label><br />
							<input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
						</div>
						<?php endif; ?>
					</li>
					<li class="wide">
						<label for="shipping:street1"><?php echo $this->__('Address') ?> <span class="required">*</span></label><br />
						<input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingStreet(1)) ?>" class="required-entry input-text"/>
						<?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
						<input type="text" title="<?php echo $this->__('Street Address '.$_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingStreet($_i)) ?>" class="input-text" />
						<?php endfor ?>
					</li>
					<li>
						<div  class="input-box">
							<label for="shipping:country_id"><?php echo $this->__('Country') ?> <span class="required">*</span></label><br />
							<?php echo $this->getCountryHtmlSelect('shipping') ?>
						</div>
						<?php if ($this->configData['show_region']):?>
						<div  class="input-box">
							<label for="shipping:region"><?php echo $this->__('State/Province') ?> <span class="required">*</span></label><br/>
							<select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;width:135px;" >
									<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
							</select>
							<script type="text/javascript">
									$('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getShippingRegionId() ?>");
							</script>
							<input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none" />
						</div>
						<?php endif;?>
					</li>
					<li>
						<?php if($this->configData['show_city']): ?>
						<div class="input-box">
							<label for="shipping:city"><?php echo $this->__('City') ?> <span class="required">*</span></label><br />
							<input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingCity()) ?>" class="required-entry input-text" id="shipping:city" />
						</div>
						<?php endif;?>
						
						<?php if($this->configData['show_zipcode']): ?>
							<div class="input-box">
								<label for="shipping:postcode"><?php echo $this->__('Zip/Postal Code') ?> <span class="required">*</span></label><br />
								<input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingZipcode()) ?>" class="validate-zip-international required-entry input-text"/>
							</div>
						<?php endif;?>
					</li>
					<li>
						<?php if($this->configData['show_telephone']): ?>
						<div class="input-box">
							<label for="shipping:telephone"><?php echo $this->__('Telephone') ?> <span class="required">*</span></label><br/>
							<input type="text" name="shipping[telephone]" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="required-entry input-text" id="shipping:telephone" />
						</div>
						<?php endif; ?>
						
						<?php if($this->configData['show_fax']): ?>
						<div class="input-box">
							<label for="shipping:fax"><?php echo $this->__('Fax') ?></label><br/>
							<input type="text" name="shipping[fax]" value="<?php echo $this->htmlEscape($this->getShippingAddress()->getShippingFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text" id="shipping:fax" />
						</div>
						<?php endif; ?>
					</li>	  
			<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
				<li><input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" <?php if ($this->getShippingAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> /> <label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></li>
			<?php else:?>
				<li><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
			<?php endif;?>
			</ul>
			</fieldset> 
			
		</div>
		<?php */ ?>
		
	</div>
</div>	
<?php endif;?>
<script type="text/javascript">
//<![CDATA[	
<?php if ($this->isShowShippingAddress()):?>
	<?php if ($this->configData['show_region']):?>
	var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
	<?php endif;?>
	if ($('shipping:different_shipping')) {
		Event.observe('shipping:different_shipping', 'click', function() {
			if ($('shipping:different_shipping').checked) {
				$('billing:use_for_shipping').value = '0';
				$('showhide_shipping').style.display = 'block';
				<?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod()):?>
					change_class_name($('shipping_method_step_header'), 2, 3);
					change_class_name($('payment_method_step_header'), 3, 4);
					change_class_name($('review_step_header'), 4, 5);		
				<?php else:?>
					change_class_name($('payment_method_step_header'), 2, 3);
					change_class_name($('review_step_header'), 3, 4);
				<?php endif;?>
			}
			else {
				$('billing:use_for_shipping').value = '1';
				$('showhide_shipping').style.display = 'none';
				<?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod()):?>
					change_class_name($('shipping_method_step_header'), 3, 2);
					change_class_name($('payment_method_step_header'), 4, 3);
					change_class_name($('review_step_header'), 5, 4);
				<?php else:?>
					change_class_name($('payment_method_step_header'), 3, 2);
					change_class_name($('review_step_header'), 4, 3);
				<?php endif;?>
			}
			
			//<!-- if show different shipping address, save billing & shipping address when customer check the checkbox-->
			<?php if ($this->configData['enable_ajax']):?>
			save_address_information(save_address_url);
			<?php endif;?>
		});
	}
	if ($('shipping-address-select')) {
		Event.observe('shipping-address-select', 'change', function() {
			var isNew = $('shipping-address-select').value ? false : true;
			setNewAddress(isNew, 'shipping', save_address_url);
		});
	}
<?php endif;?>
//]]>
</script>